<?php

namespace App\Modules\StockGroup\Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\StockGroup\Models\StockGroup;
use Illuminate\Support\Facades\DB;

class StockGroupSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('stock_groups')->insert([
            [
                'id' => 1,
                'name' => 'Primary',
                'code' => 'PRI',
                'description' => 'Top-level stock group for lab test classifications.',
                'status' => 'active',
                'icon' => 'lucide-layers',
                'parent_id' => null,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔹 Biochemistry
            [
                'id' => 2,
                'name' => 'Liver Function Test (LFT)',
                'code' => 'BIO-LFT',
                'description' => 'Assesses liver health by measuring enzymes and bilirubin levels.',
                'status' => 'active',
                'icon' => 'lucide-flask-conical',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Kidney Function Test (KFT)',
                'code' => 'BIO-KFT',
                'description' => 'Evaluates kidney performance by measuring creatinine, urea, and other waste levels in blood.',
                'status' => 'active',
                'icon' => 'lucide-droplet',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔹 Hematology
            [
                'id' => 4,
                'name' => 'Complete Blood Count (CBC)',
                'code' => 'HEM-CBC',
                'description' => 'Analyzes blood components like RBC, WBC, and platelets.',
                'status' => 'active',
                'icon' => 'lucide-droplets',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Coagulation Profile',
                'code' => 'HEM-COAG',
                'description' => 'Checks clotting time and related parameters.',
                'status' => 'active',
                'icon' => 'lucide-activity',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔹 Microbiology
            [
                'id' => 6,
                'name' => 'Urine Culture',
                'code' => 'MIC-URC',
                'description' => 'Detects bacteria in urine to identify infections.',
                'status' => 'active',
                'icon' => 'lucide-bacteria',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Sputum Culture',
                'code' => 'MIC-SPT',
                'description' => 'Analyzes sputum samples for bacterial infections.',
                'status' => 'active',
                'icon' => 'lucide-lungs',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔹 Immunology
            [
                'id' => 8,
                'name' => 'Thyroid Profile',
                'code' => 'IMM-THY',
                'description' => 'Tests for T3, T4, and TSH hormone levels.',
                'status' => 'active',
                'icon' => 'lucide-shield-check',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Vitamin Profile',
                'code' => 'IMM-VIT',
                'description' => 'Checks Vitamin D, B12, and other essential nutrients.',
                'status' => 'active',
                'icon' => 'lucide-sparkles',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🔹 Serology
            [
                'id' => 10,
                'name' => 'HIV Test',
                'code' => 'SER-HIV',
                'description' => 'Detects antibodies against HIV virus.',
                'status' => 'active',
                'icon' => 'lucide-heart-pulse',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Hepatitis Profile',
                'code' => 'SER-HEP',
                'description' => 'Screening for Hepatitis A, B, and C viruses.',
                'status' => 'active',
                'icon' => 'lucide-thermometer',
                'parent_id' => 1,
                'should_quantities_of_items_be_added' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'id' => 1,
            //     'name' => 'Primary',
            //     'code' => 'PRI',
            //     'description' => 'Top level stock group',
            //     'status' => 'active',
            //     'icon' => 'lucide-layers',
            //     'parent_id' => null,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 2,
            //     'name' => 'Raw Materials',
            //     'code' => 'RAW',
            //     'description' => 'Base materials used for production',
            //     'status' => 'active',
            //     'icon' => 'lucide-cube',
            //     'parent_id' => 1,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 3,
            //     'name' => 'Finished Goods',
            //     'code' => 'FG',
            //     'description' => 'Manufactured finished products',
            //     'status' => 'active',
            //     'icon' => 'lucide-package',
            //     'parent_id' => 1,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 4,
            //     'name' => 'Consumables',
            //     'code' => 'CON',
            //     'description' => 'Items consumed during production',
            //     'status' => 'active',
            //     'icon' => 'lucide-droplet',
            //     'parent_id' => 1,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 5,
            //     'name' => 'Electronics',
            //     'code' => 'ELEC',
            //     'description' => 'Electronic finished goods',
            //     'status' => 'active',
            //     'icon' => 'lucide-tv',
            //     'parent_id' => 3, // under Finished Goods
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 6,
            //     'name' => 'Mobiles',
            //     'code' => 'MOB',
            //     'description' => 'Mobile phones',
            //     'status' => 'active',
            //     'icon' => 'lucide-smartphone',
            //     'parent_id' => 5,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 7,
            //     'name' => 'Laptops',
            //     'code' => 'LAP',
            //     'description' => 'Laptops and notebooks',
            //     'status' => 'active',
            //     'icon' => 'lucide-laptop',
            //     'parent_id' => 5,
            //     'should_quantities_of_items_be_added' => true,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ]);
    }
}
