<?php

namespace App\Modules\VoucherType\Database\Seeders;
use DB;
use Illuminate\Database\Seeder;
use App\Modules\VoucherType\Models\VoucherType;

class VoucherTypeSeeder extends Seeder
{
    public function run(): void
    {
        // VoucherType::create(['name' => 'Sample VoucherType']);
        $voucherTypes = [
            // Accounting Category (ID 1)
            [
                'id' => 1,
                'name' => 'Payment Voucher',
                'code' => 'PAYM',
                'voucher_category_id' => 1,
                'description' => 'For payments to suppliers or truck drivers',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaMoneyBill',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Receipt Voucher',
                'code' => 'RCVP',
                'voucher_category_id' => 1,
                'description' => 'For receipts from distributors',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaMoneyCheck',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Contra Voucher',
                'code' => 'CNTR',
                'voucher_category_id' => 1,
                'description' => 'For transfers between bank accounts or cash to bank',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaExchangeAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Journal Voucher',
                'code' => 'JRNL',
                'voucher_category_id' => 1,
                'description' => 'For adjustments, accruals, and opening balances',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaBook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Reversing Journal',
                'code' => 'RVJL',
                'voucher_category_id' => 1,
                'description' => 'For reversing previous journal entries',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaUndo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Memo Voucher',
                'code' => 'MEMO',
                'voucher_category_id' => 1,
                'description' => 'For memorandum entries (non-posting)',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaStickyNote',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Inventory Category (ID 2)
            [
                'id' => 7,
                'name' => 'Purchase Voucher',
                'code' => 'PURC',
                'voucher_category_id' => 2,
                'description' => 'For goods received from suppliers like ACC',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaCartPlus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Sales Voucher',
                'code' => 'SALE',
                'voucher_category_id' => 2,
                'description' => 'For goods sold to distributors',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaCartArrowDown',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Delivery Voucher',
                'code' => 'DLVR',
                'voucher_category_id' => 2,
                'description' => 'For goods dispatched to distributors',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaTruck',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Receipt Note Voucher',
                'code' => 'RCNT',
                'voucher_category_id' => 2,
                'description' => 'For goods received without invoice',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaReceipt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Rejection In Voucher',
                'code' => 'RJIN',
                'voucher_category_id' => 2,
                'description' => 'For rejected goods returned from distributors',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaTimesCircle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Rejection Out Voucher',
                'code' => 'RJOT',
                'voucher_category_id' => 2,
                'description' => 'For rejected goods returned to suppliers',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaBan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Transfer Voucher',
                'code' => 'TRNS',
                'voucher_category_id' => 2,
                'description' => 'For internal godown transfers',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaExchange',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Manufacturing Journal',
                'code' => 'MANJ',
                'voucher_category_id' => 2,
                'description' => 'For recording manufacturing processes',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaIndustry',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Physical Stock Voucher',
                'code' => 'PHSK',
                'voucher_category_id' => 2,
                'description' => 'For physical stock adjustments',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaClipboardCheck',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Statutory Category (ID 3)
            [
                'id' => 16,
                'name' => 'Provident Fund Voucher',
                'code' => 'PFND',
                'voucher_category_id' => 3,
                'description' => 'For PF contributions',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaShieldAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'ESI Payment Voucher',
                'code' => 'ESIP',
                'voucher_category_id' => 3,
                'description' => 'For Employee State Insurance payments',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaUserShield',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Payroll Category (ID 4)
            [
                'id' => 18,
                'name' => 'Salary Payment Voucher',
                'code' => 'SLRY',
                'voucher_category_id' => 4,
                'description' => 'For employee salary disbursements',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaMoneyBillWave',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Bonus Voucher',
                'code' => 'BONS',
                'voucher_category_id' => 4,
                'description' => 'For employee bonus payments',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaGift',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Attendance Voucher',
                'code' => 'ATND',
                'voucher_category_id' => 4,
                'description' => 'For recording employee attendance',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaClock',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Payroll Voucher',
                'code' => 'PYRL',
                'voucher_category_id' => 4,
                'description' => 'For overall payroll processing',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaUsersCog',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Order Category (ID 5)
            [
                'id' => 22,
                'name' => 'Purchase Order Voucher',
                'code' => 'POVD',
                'voucher_category_id' => 5,
                'description' => 'For placing purchase orders with suppliers',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaShoppingBag',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Sales Order Voucher',
                'code' => 'SOVD',
                'voucher_category_id' => 5,
                'description' => 'For receiving sales orders from distributors',
                'is_financial' => false,
                'status' => 'active',
                'icon' => 'FaFileInvoice',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Assets Category (ID 6)
            [
                'id' => 24,
                'name' => 'Asset Acquisition Voucher',
                'code' => 'ACQT',
                'voucher_category_id' => 6,
                'description' => 'For purchasing fixed assets like trucks or machinery',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaPlusSquare',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Depreciation Voucher',
                'code' => 'DEPR',
                'voucher_category_id' => 6,
                'description' => 'For recording asset depreciation',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaChartLine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Asset Disposal Voucher',
                'code' => 'DSPL',
                'voucher_category_id' => 6,
                'description' => 'For disposing of fixed assets',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaTrash',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Liabilities Category (ID 7)
            [
                'id' => 27,
                'name' => 'Loan Repayment Voucher',
                'code' => 'LNRP',
                'voucher_category_id' => 7,
                'description' => 'For repaying loans or mortgages',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaHandHoldingUsd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Interest Payment Voucher',
                'code' => 'INTP',
                'voucher_category_id' => 7,
                'description' => 'For paying interest on loans',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaPercentage',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Expenses Category (ID 8)
            [
                'id' => 29,
                'name' => 'Rent Payment Voucher',
                'code' => 'RNTP',
                'voucher_category_id' => 8,
                'description' => 'For paying rent for warehouses or offices',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaHome',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Utility Bill Voucher',
                'code' => 'UTLB',
                'voucher_category_id' => 8,
                'description' => 'For paying utility bills (electricity, water)',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaBolt',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tax Category (ID 9)
            [
                'id' => 31,
                'name' => 'GST Input Voucher',
                'code' => 'GSTI',
                'voucher_category_id' => 9,
                'description' => 'For recording GST input tax credits',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaFileImport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'GST Output Voucher',
                'code' => 'GSTO',
                'voucher_category_id' => 9,
                'description' => 'For recording GST output tax liabilities',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaFileExport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'TDS Payment Voucher',
                'code' => 'TDSP',
                'voucher_category_id' => 9,
                'description' => 'For TDS payments to government',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaHandHolding',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'TCS Payment Voucher',
                'code' => 'TCSP',
                'voucher_category_id' => 9,
                'description' => 'For TCS payments to government',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaCoins',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Advance Tax Voucher',
                'code' => 'ADTX',
                'voucher_category_id' => 9,
                'description' => 'For advance tax payments',
                'is_financial' => true,
                'status' => 'active',
                'icon' => 'FaCalendarAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($voucherTypes as $type) {
            VoucherType::updateOrCreate(
                ['id' => $type['id']],
                $type
            );
        }


    }
}
